# ${CLIENT_NAME} — Environment
# Generated by monoliet-wp-factory create-site.sh

CLIENT_SLUG=${CLIENT_SLUG}
CLIENT_NAME=${CLIENT_NAME}
CLIENT_DOMAIN=${CLIENT_DOMAIN}

# Database (shared MariaDB)
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}

# WordPress admin
WP_ADMIN_USER=monoliet
WP_ADMIN_PASS=${WP_ADMIN_PASS}
WP_ADMIN_EMAIL=sites@monoliet.cloud

# Monoliet API
MONOLIET_API_KEY=${MONOLIET_API_KEY}

# VPS
VPS_IP=${VPS_IP}
