#!/bin/sh
# create-site.sh — Scaffold a new client WordPress site from templates.
#
# Usage: ./scripts/create-site.sh <slug> <name> <domain>
# Example: ./scripts/create-site.sh empire-ink "Empire INK" empire-ink.nl
set -e

FACTORY_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [ $# -lt 3 ]; then
    echo "Usage: $0 <slug> <name> <domain>"
    echo "Example: $0 empire-ink \"Empire INK\" empire-ink.nl"
    exit 1
fi

CLIENT_SLUG="$1"
CLIENT_NAME="$2"
CLIENT_DOMAIN="$3"

DB_NAME="wp_$(echo "$CLIENT_SLUG" | tr '-' '_')"
DB_USER="wp_$(echo "$CLIENT_SLUG" | tr '-' '_')"
DB_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
WP_ADMIN_PASS="$(openssl rand -base64 18 | tr -d '/+=' | head -c 24)"
MONOLIET_API_KEY="$(openssl rand -hex 32)"
VPS_IP="72.62.26.15"

CLIENT_DIR="$FACTORY_DIR/clients/$CLIENT_SLUG"

echo "==> Creating client site: $CLIENT_NAME ($CLIENT_SLUG)"
echo "    Domain: $CLIENT_DOMAIN"
echo "    Directory: $CLIENT_DIR"
echo ""

if [ -d "$CLIENT_DIR" ]; then
    echo "!!! Directory already exists: $CLIENT_DIR"
    echo "    Remove it first or choose a different slug."
    exit 1
fi

mkdir -p "$CLIENT_DIR/wp/wp-content/themes"
mkdir -p "$CLIENT_DIR/backups"

export CLIENT_SLUG CLIENT_NAME CLIENT_DOMAIN
export DB_NAME DB_USER DB_PASSWORD WP_ADMIN_PASS MONOLIET_API_KEY VPS_IP

echo "==> Processing templates..."

for tpl in "$FACTORY_DIR/templates/"*.tpl; do
    filename="$(basename "$tpl" .tpl)"
    envsubst < "$tpl" > "$CLIENT_DIR/$filename"
    echo "    Created: $filename"
done

chmod +x "$CLIENT_DIR/init.sh" "$CLIENT_DIR/deploy.sh" "$CLIENT_DIR/backup.sh" "$CLIENT_DIR/maintain.sh"

echo "==> Copying base theme..."
cp -r "$FACTORY_DIR/base-theme" "$CLIENT_DIR/wp/wp-content/themes/monoliet-starter"

echo "==> Copying monoliet-core to shared-plugins (if not present)..."
SHARED_PLUGINS="$FACTORY_DIR/shared-plugins"
if [ ! -d "$SHARED_PLUGINS/monoliet-core" ]; then
    mkdir -p "$SHARED_PLUGINS"
    cp -r "$FACTORY_DIR/monoliet-core" "$SHARED_PLUGINS/monoliet-core"
    echo "    monoliet-core copied to shared-plugins."
else
    echo "    monoliet-core already in shared-plugins, skipping."
fi

echo "==> Writing client.json..."
cat > "$CLIENT_DIR/client.json" << JSONEOF
{
    "slug": "$CLIENT_SLUG",
    "name": "$CLIENT_NAME",
    "domain": "$CLIENT_DOMAIN",
    "db_name": "$DB_NAME",
    "db_user": "$DB_USER",
    "container": "wp-$CLIENT_SLUG",
    "created": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    "vps_path": "/opt/docker/clients/$CLIENT_SLUG"
}
JSONEOF

echo "==> Initializing git repo..."
cd "$CLIENT_DIR"
git init
git add -A
git commit -m "Initial scaffold for $CLIENT_NAME

Generated by monoliet-wp-factory create-site.sh"

echo ""
echo "========================================="
echo "  Site scaffolded: $CLIENT_NAME"
echo "========================================="
echo ""
echo "  Directory: $CLIENT_DIR"
echo "  Domain:    $CLIENT_DOMAIN"
echo ""
echo "  DB Name:      $DB_NAME"
echo "  DB User:      $DB_USER"
echo "  DB Password:  $DB_PASSWORD"
echo ""
echo "  WP Admin:     monoliet"
echo "  WP Password:  $WP_ADMIN_PASS"
echo "  API Key:      $MONOLIET_API_KEY"
echo ""
echo "  NEXT STEPS:"
echo "  1. Create GitHub repo and push:"
echo "     git remote add origin https://github.com/AMvdBM19/$CLIENT_SLUG.git"
echo "     git push -u origin main"
echo ""
echo "  2. Customize client.css with brand colors"
echo ""
echo "  3. Deploy to VPS:"
echo "     ./scripts/deploy-client.sh $CLIENT_SLUG"
echo ""
echo "  4. Add proxy host in nginx-proxy-manager:"
echo "     Domain: $CLIENT_DOMAIN"
echo "     Forward: wp-$CLIENT_SLUG:80"
echo "     SSL: Request new Let's Encrypt certificate"
echo ""
echo "  5. Point DNS A record:"
echo "     $CLIENT_DOMAIN → $VPS_IP"
echo "========================================="
